import './globals.css'
import type { Metadata } from 'next'
import { Inter, Lato } from 'next/font/google'
import { GeneralContextProvider } from './context/GeneralContext'
import { redirect } from 'next/navigation';
import { cookies } from 'next/headers';
import LoginRedirect from './components/LoginRedirect';
import { headers } from "next/headers";
import { AuthContextProvider } from './context/AuthContext';
import InviteModal from './components/Modals/InviteModal';
import WorkspaceModal from './components/Modals/WorkspaceModal';
import { ThemeProvider } from './theme-provider';

const inter = Inter({ subsets: ['latin'] })
const lato = Lato({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Slack Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthContextProvider>
      <GeneralContextProvider>
        <html lang="en">
          <body className={lato.className}>
            <InviteModal />
            <WorkspaceModal />
            {children}
          </body>
        </html>
      </GeneralContextProvider>
    </AuthContextProvider>
  )
}

// function getSession() {
//   return fetch('http://localhost:8000/api/session').then(res => res.json());
// }
